/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as wwwLayoutRouteImport } from './app/(www)/layout'
import { Route as wwwPageRouteImport } from './app/(www)/page'
import { Route as wwwauthLayoutRouteImport } from './app/(www)/(auth)/layout'
import { Route as wwwProfilePageRouteImport } from './app/(www)/profile/page'
import { Route as wwwProductsPageRouteImport } from './app/(www)/products/page'
import { Route as wwwPrivacyPageRouteImport } from './app/(www)/privacy/page'
import { Route as wwwExchangesPageRouteImport } from './app/(www)/exchanges/page'
import { Route as wwwEditorPageRouteImport } from './app/(www)/editor/page'
import { Route as wwwContactPageRouteImport } from './app/(www)/contact/page'
import { Route as wwwCheckoutPageRouteImport } from './app/(www)/checkout/page'
import { Route as wwwCategoriesPageRouteImport } from './app/(www)/categories/page'
import { Route as wwwAboutPageRouteImport } from './app/(www)/about/page'
import { Route as wwwProductsProductIdRouteImport } from './app/(www)/products/$productId'
import { Route as wwwProfileSecurityPageRouteImport } from './app/(www)/profile/security/page'
import { Route as wwwProfilePaymentsPageRouteImport } from './app/(www)/profile/payments/page'
import { Route as wwwProfileOrdersPageRouteImport } from './app/(www)/profile/orders/page'
import { Route as wwwProfileMePageRouteImport } from './app/(www)/profile/me/page'
import { Route as wwwProfileAddressPageRouteImport } from './app/(www)/profile/address/page'
import { Route as wwwProfileAccountPageRouteImport } from './app/(www)/profile/account/page'
import { Route as wwwauthRegisterPageRouteImport } from './app/(www)/(auth)/register/page'
import { Route as wwwauthLoginPageRouteImport } from './app/(www)/(auth)/login/page'
import { Route as wwwauthRegisterValidationTokenRouteImport } from './app/(www)/(auth)/register/$validationToken'

const wwwLayoutRoute = wwwLayoutRouteImport.update({
  id: '/(www)',
  getParentRoute: () => rootRouteImport,
} as any)
const wwwPageRoute = wwwPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwauthLayoutRoute = wwwauthLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwProfilePageRoute = wwwProfilePageRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwProductsPageRoute = wwwProductsPageRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwPrivacyPageRoute = wwwPrivacyPageRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwExchangesPageRoute = wwwExchangesPageRouteImport.update({
  id: '/exchanges/',
  path: '/exchanges/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwEditorPageRoute = wwwEditorPageRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwContactPageRoute = wwwContactPageRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwCheckoutPageRoute = wwwCheckoutPageRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwCategoriesPageRoute = wwwCategoriesPageRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwAboutPageRoute = wwwAboutPageRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwProductsProductIdRoute = wwwProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwProfileSecurityPageRoute = wwwProfileSecurityPageRouteImport.update({
  id: '/profile/security/',
  path: '/profile/security/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwProfilePaymentsPageRoute = wwwProfilePaymentsPageRouteImport.update({
  id: '/profile/payments/',
  path: '/profile/payments/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwProfileOrdersPageRoute = wwwProfileOrdersPageRouteImport.update({
  id: '/profile/orders/',
  path: '/profile/orders/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwProfileMePageRoute = wwwProfileMePageRouteImport.update({
  id: '/profile/me/',
  path: '/profile/me/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwProfileAddressPageRoute = wwwProfileAddressPageRouteImport.update({
  id: '/profile/address/',
  path: '/profile/address/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwProfileAccountPageRoute = wwwProfileAccountPageRouteImport.update({
  id: '/profile/account/',
  path: '/profile/account/',
  getParentRoute: () => wwwLayoutRoute,
} as any)
const wwwauthRegisterPageRoute = wwwauthRegisterPageRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => wwwauthLayoutRoute,
} as any)
const wwwauthLoginPageRoute = wwwauthLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => wwwauthLayoutRoute,
} as any)
const wwwauthRegisterValidationTokenRoute =
  wwwauthRegisterValidationTokenRouteImport.update({
    id: '/register/$validationToken',
    path: '/register/$validationToken',
    getParentRoute: () => wwwauthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof wwwPageRoute
  '/products/$productId': typeof wwwProductsProductIdRoute
  '/about': typeof wwwAboutPageRoute
  '/categories': typeof wwwCategoriesPageRoute
  '/checkout': typeof wwwCheckoutPageRoute
  '/contact': typeof wwwContactPageRoute
  '/editor': typeof wwwEditorPageRoute
  '/exchanges': typeof wwwExchangesPageRoute
  '/privacy': typeof wwwPrivacyPageRoute
  '/products': typeof wwwProductsPageRoute
  '/profile': typeof wwwProfilePageRoute
  '/register/$validationToken': typeof wwwauthRegisterValidationTokenRoute
  '/login': typeof wwwauthLoginPageRoute
  '/register': typeof wwwauthRegisterPageRoute
  '/profile/account': typeof wwwProfileAccountPageRoute
  '/profile/address': typeof wwwProfileAddressPageRoute
  '/profile/me': typeof wwwProfileMePageRoute
  '/profile/orders': typeof wwwProfileOrdersPageRoute
  '/profile/payments': typeof wwwProfilePaymentsPageRoute
  '/profile/security': typeof wwwProfileSecurityPageRoute
}
export interface FileRoutesByTo {
  '/': typeof wwwPageRoute
  '/products/$productId': typeof wwwProductsProductIdRoute
  '/about': typeof wwwAboutPageRoute
  '/categories': typeof wwwCategoriesPageRoute
  '/checkout': typeof wwwCheckoutPageRoute
  '/contact': typeof wwwContactPageRoute
  '/editor': typeof wwwEditorPageRoute
  '/exchanges': typeof wwwExchangesPageRoute
  '/privacy': typeof wwwPrivacyPageRoute
  '/products': typeof wwwProductsPageRoute
  '/profile': typeof wwwProfilePageRoute
  '/register/$validationToken': typeof wwwauthRegisterValidationTokenRoute
  '/login': typeof wwwauthLoginPageRoute
  '/register': typeof wwwauthRegisterPageRoute
  '/profile/account': typeof wwwProfileAccountPageRoute
  '/profile/address': typeof wwwProfileAddressPageRoute
  '/profile/me': typeof wwwProfileMePageRoute
  '/profile/orders': typeof wwwProfileOrdersPageRoute
  '/profile/payments': typeof wwwProfilePaymentsPageRoute
  '/profile/security': typeof wwwProfileSecurityPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(www)': typeof wwwLayoutRouteWithChildren
  '/(www)/(auth)': typeof wwwauthLayoutRouteWithChildren
  '/(www)/': typeof wwwPageRoute
  '/(www)/products/$productId': typeof wwwProductsProductIdRoute
  '/(www)/about/': typeof wwwAboutPageRoute
  '/(www)/categories/': typeof wwwCategoriesPageRoute
  '/(www)/checkout/': typeof wwwCheckoutPageRoute
  '/(www)/contact/': typeof wwwContactPageRoute
  '/(www)/editor/': typeof wwwEditorPageRoute
  '/(www)/exchanges/': typeof wwwExchangesPageRoute
  '/(www)/privacy/': typeof wwwPrivacyPageRoute
  '/(www)/products/': typeof wwwProductsPageRoute
  '/(www)/profile/': typeof wwwProfilePageRoute
  '/(www)/(auth)/register/$validationToken': typeof wwwauthRegisterValidationTokenRoute
  '/(www)/(auth)/login/': typeof wwwauthLoginPageRoute
  '/(www)/(auth)/register/': typeof wwwauthRegisterPageRoute
  '/(www)/profile/account/': typeof wwwProfileAccountPageRoute
  '/(www)/profile/address/': typeof wwwProfileAddressPageRoute
  '/(www)/profile/me/': typeof wwwProfileMePageRoute
  '/(www)/profile/orders/': typeof wwwProfileOrdersPageRoute
  '/(www)/profile/payments/': typeof wwwProfilePaymentsPageRoute
  '/(www)/profile/security/': typeof wwwProfileSecurityPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products/$productId'
    | '/about'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/editor'
    | '/exchanges'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/register/$validationToken'
    | '/login'
    | '/register'
    | '/profile/account'
    | '/profile/address'
    | '/profile/me'
    | '/profile/orders'
    | '/profile/payments'
    | '/profile/security'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products/$productId'
    | '/about'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/editor'
    | '/exchanges'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/register/$validationToken'
    | '/login'
    | '/register'
    | '/profile/account'
    | '/profile/address'
    | '/profile/me'
    | '/profile/orders'
    | '/profile/payments'
    | '/profile/security'
  id:
    | '__root__'
    | '/(www)'
    | '/(www)/(auth)'
    | '/(www)/'
    | '/(www)/products/$productId'
    | '/(www)/about/'
    | '/(www)/categories/'
    | '/(www)/checkout/'
    | '/(www)/contact/'
    | '/(www)/editor/'
    | '/(www)/exchanges/'
    | '/(www)/privacy/'
    | '/(www)/products/'
    | '/(www)/profile/'
    | '/(www)/(auth)/register/$validationToken'
    | '/(www)/(auth)/login/'
    | '/(www)/(auth)/register/'
    | '/(www)/profile/account/'
    | '/(www)/profile/address/'
    | '/(www)/profile/me/'
    | '/(www)/profile/orders/'
    | '/(www)/profile/payments/'
    | '/(www)/profile/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  wwwLayoutRoute: typeof wwwLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(www)': {
      id: '/(www)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof wwwLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(www)/': {
      id: '/(www)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof wwwPageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/(auth)': {
      id: '/(www)/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof wwwauthLayoutRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/profile/': {
      id: '/(www)/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof wwwProfilePageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/products/': {
      id: '/(www)/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof wwwProductsPageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/privacy/': {
      id: '/(www)/privacy/'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof wwwPrivacyPageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/exchanges/': {
      id: '/(www)/exchanges/'
      path: '/exchanges'
      fullPath: '/exchanges'
      preLoaderRoute: typeof wwwExchangesPageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/editor/': {
      id: '/(www)/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof wwwEditorPageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/contact/': {
      id: '/(www)/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof wwwContactPageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/checkout/': {
      id: '/(www)/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof wwwCheckoutPageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/categories/': {
      id: '/(www)/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof wwwCategoriesPageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/about/': {
      id: '/(www)/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof wwwAboutPageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/products/$productId': {
      id: '/(www)/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof wwwProductsProductIdRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/profile/security/': {
      id: '/(www)/profile/security/'
      path: '/profile/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof wwwProfileSecurityPageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/profile/payments/': {
      id: '/(www)/profile/payments/'
      path: '/profile/payments'
      fullPath: '/profile/payments'
      preLoaderRoute: typeof wwwProfilePaymentsPageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/profile/orders/': {
      id: '/(www)/profile/orders/'
      path: '/profile/orders'
      fullPath: '/profile/orders'
      preLoaderRoute: typeof wwwProfileOrdersPageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/profile/me/': {
      id: '/(www)/profile/me/'
      path: '/profile/me'
      fullPath: '/profile/me'
      preLoaderRoute: typeof wwwProfileMePageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/profile/address/': {
      id: '/(www)/profile/address/'
      path: '/profile/address'
      fullPath: '/profile/address'
      preLoaderRoute: typeof wwwProfileAddressPageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/profile/account/': {
      id: '/(www)/profile/account/'
      path: '/profile/account'
      fullPath: '/profile/account'
      preLoaderRoute: typeof wwwProfileAccountPageRouteImport
      parentRoute: typeof wwwLayoutRoute
    }
    '/(www)/(auth)/register/': {
      id: '/(www)/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof wwwauthRegisterPageRouteImport
      parentRoute: typeof wwwauthLayoutRoute
    }
    '/(www)/(auth)/login/': {
      id: '/(www)/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof wwwauthLoginPageRouteImport
      parentRoute: typeof wwwauthLayoutRoute
    }
    '/(www)/(auth)/register/$validationToken': {
      id: '/(www)/(auth)/register/$validationToken'
      path: '/register/$validationToken'
      fullPath: '/register/$validationToken'
      preLoaderRoute: typeof wwwauthRegisterValidationTokenRouteImport
      parentRoute: typeof wwwauthLayoutRoute
    }
  }
}

interface wwwauthLayoutRouteChildren {
  wwwauthRegisterValidationTokenRoute: typeof wwwauthRegisterValidationTokenRoute
  wwwauthLoginPageRoute: typeof wwwauthLoginPageRoute
  wwwauthRegisterPageRoute: typeof wwwauthRegisterPageRoute
}

const wwwauthLayoutRouteChildren: wwwauthLayoutRouteChildren = {
  wwwauthRegisterValidationTokenRoute: wwwauthRegisterValidationTokenRoute,
  wwwauthLoginPageRoute: wwwauthLoginPageRoute,
  wwwauthRegisterPageRoute: wwwauthRegisterPageRoute,
}

const wwwauthLayoutRouteWithChildren = wwwauthLayoutRoute._addFileChildren(
  wwwauthLayoutRouteChildren,
)

interface wwwLayoutRouteChildren {
  wwwauthLayoutRoute: typeof wwwauthLayoutRouteWithChildren
  wwwPageRoute: typeof wwwPageRoute
  wwwProductsProductIdRoute: typeof wwwProductsProductIdRoute
  wwwAboutPageRoute: typeof wwwAboutPageRoute
  wwwCategoriesPageRoute: typeof wwwCategoriesPageRoute
  wwwCheckoutPageRoute: typeof wwwCheckoutPageRoute
  wwwContactPageRoute: typeof wwwContactPageRoute
  wwwEditorPageRoute: typeof wwwEditorPageRoute
  wwwExchangesPageRoute: typeof wwwExchangesPageRoute
  wwwPrivacyPageRoute: typeof wwwPrivacyPageRoute
  wwwProductsPageRoute: typeof wwwProductsPageRoute
  wwwProfilePageRoute: typeof wwwProfilePageRoute
  wwwProfileAccountPageRoute: typeof wwwProfileAccountPageRoute
  wwwProfileAddressPageRoute: typeof wwwProfileAddressPageRoute
  wwwProfileMePageRoute: typeof wwwProfileMePageRoute
  wwwProfileOrdersPageRoute: typeof wwwProfileOrdersPageRoute
  wwwProfilePaymentsPageRoute: typeof wwwProfilePaymentsPageRoute
  wwwProfileSecurityPageRoute: typeof wwwProfileSecurityPageRoute
}

const wwwLayoutRouteChildren: wwwLayoutRouteChildren = {
  wwwauthLayoutRoute: wwwauthLayoutRouteWithChildren,
  wwwPageRoute: wwwPageRoute,
  wwwProductsProductIdRoute: wwwProductsProductIdRoute,
  wwwAboutPageRoute: wwwAboutPageRoute,
  wwwCategoriesPageRoute: wwwCategoriesPageRoute,
  wwwCheckoutPageRoute: wwwCheckoutPageRoute,
  wwwContactPageRoute: wwwContactPageRoute,
  wwwEditorPageRoute: wwwEditorPageRoute,
  wwwExchangesPageRoute: wwwExchangesPageRoute,
  wwwPrivacyPageRoute: wwwPrivacyPageRoute,
  wwwProductsPageRoute: wwwProductsPageRoute,
  wwwProfilePageRoute: wwwProfilePageRoute,
  wwwProfileAccountPageRoute: wwwProfileAccountPageRoute,
  wwwProfileAddressPageRoute: wwwProfileAddressPageRoute,
  wwwProfileMePageRoute: wwwProfileMePageRoute,
  wwwProfileOrdersPageRoute: wwwProfileOrdersPageRoute,
  wwwProfilePaymentsPageRoute: wwwProfilePaymentsPageRoute,
  wwwProfileSecurityPageRoute: wwwProfileSecurityPageRoute,
}

const wwwLayoutRouteWithChildren = wwwLayoutRoute._addFileChildren(
  wwwLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  wwwLayoutRoute: wwwLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
